<a href="https://colab.research.google.com/github/Anusree-Selvan/Learn.Py/blob/main/TASK%208.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Generate a 3 x 3 matrix using random module.

In [12]:
#please provide your answer below this line.
import numpy as np
randommatrix = np.random.rand(3,3)
print(randommatrix)

[[0.51989448 0.47468027 0.47669326]
 [0.96987006 0.16837122 0.40183463]
 [0.33433706 0.56385919 0.06592836]]


2. Generate two 4 x 4 matrix using numpy and 

 a) Reshape it to 2 x 8matrix and vertically stack it.

 b) Reshape it to 2 x 8 matrix and horizontally stack it.

In [13]:
#please provide your answer below this line.
import numpy as np
m = np.arange(2,18).reshape(4,4)
print(m)
n = np.arange(5,21).reshape(4,4)
print(n)
m = np.arange(2,18).reshape(2,8)
n = np.arange(5,21).reshape(2,8)
i = np.vstack((m,n))
print(i)
j = np.hstack((m,n))
print(j)

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]
 [14 15 16 17]]
[[ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]
[[ 2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17]
 [ 5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20]]
[[ 2  3  4  5  6  7  8  9  5  6  7  8  9 10 11 12]
 [10 11 12 13 14 15 16 17 13 14 15 16 17 18 19 20]]
